In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
import sklearn.metrics
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df = pd.read_excel("D:\Educational\Projects\Parkinsons Disease Prediction\Datasets\Cleaned Data.xlsx")
df

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        116.676       137.871       111.366         0.00997   
2        120.267       137.244       114.820         0.00333   
3        107.332       113.840       104.315         0.00290   
4         95.730       132.068        91.754         0.00551   
..           ...           ...           ...             ...   
110      170.368       268.796        79.543         0.00571   
111      198.458       219.290       148.691         0.00376   
112      202.805       231.508        86.232         0.00370   
113      202.544       241.350       164.168         0.00254   
114      223.361       263.872        87.638         0.00352   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00009   0.00502   0.00698     0.01505       0.05492   
2             0.00003   0.00155   0.00202     0.00466       0.01608   
3             0.00003   0.00144   0.00182     0.00431       0.01567   
4             0.00006   0.00293   0.00332     0.00880       0.02093   
..                ...       ...       ...         ...           ...   
110           0.00003   0.00232   0.00269     0.00696       0.03273   
111           0.00002   0.00182   0.00215     0.00546       0.03527   
112           0.00002   0.00189   0.00211     0.00568       0.01997   
113           0.00001   0.00100   0.00133     0.00301       0.02662   
114           0.00002   0.00169   0.00188     0.00506       0.02536   

     MDVP:Shimmer(dB)  ...  Shimmer:DDA      NHR     HNR      RPDE       DFA  \
0               0.426  ...      0.06545  0.02211  21.033  0.414783  0.815285   
1               0.517  ...      0.08771  0.01353  20.644  0.434969  0.819235   
2               0.140  ...      0.02337  0.00607  24.886  0.596040  0.764112   
3               0.134  ...      0.02487  0.00344  26.892  0.637420  0.763262   
4               0.191  ...      0.03218  0.01070  21.812  0.615551  0.773587   
..                ...  ...          ...      ...     ...       ...       ...   
110             0.281  ...      0.05139  0.02485  18.540  0.677131  0.685057   
111             0.297  ...      0.06165  0.01728  18.702  0.606273  0.661735   
112             0.180  ...      0.03350  0.02010  18.687  0.536102  0.632631   
113             0.228  ...      0.04426  0.01049  20.680  0.497480  0.630409   
114             0.225  ...      0.04137  0.01493  20.366  0.566849  0.574282   

      spread1   spread2        D2       PPE  status  
0   -4.813031  0.266482  2.301442  0.284654       1  
1   -4.117501  0.334147  2.405554  0.368975       1  
2   -5.634322  0.257682  1.854785  0.211756       1  
3   -6.167603  0.183721  2.064693  0.163755       1  
4   -5.498678  0.327769  2.322511  0.231571       1  
..        ...       ...       ...       ...     ...  
110 -4.796845  0.397749  2.963799  0.277227       0  
111 -5.585259  0.310746  2.465528  0.209863       0  
112 -5.898673  0.213353  2.470746  0.189032       0  
113 -6.132663  0.220617  2.576563  0.159777       0  
114 -5.456811  0.345238  2.840556  0.232861       0  

[115 rows x 23 columns]

## Feature Engineering

In [3]:
x = df.drop(['status'], axis= 1)
x

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0        119.992       157.302        74.997         0.00784   
1        116.676       137.871       111.366         0.00997   
2        120.267       137.244       114.820         0.00333   
3        107.332       113.840       104.315         0.00290   
4         95.730       132.068        91.754         0.00551   
..           ...           ...           ...             ...   
110      170.368       268.796        79.543         0.00571   
111      198.458       219.290       148.691         0.00376   
112      202.805       231.508        86.232         0.00370   
113      202.544       241.350       164.168         0.00254   
114      223.361       263.872        87.638         0.00352   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
0             0.00007   0.00370   0.00554     0.01109       0.04374   
1             0.00009   0.00502   0.00698     0.01505       0.05492   
2             0.00003   0.00155   0.00202     0.00466       0.01608   
3             0.00003   0.00144   0.00182     0.00431       0.01567   
4             0.00006   0.00293   0.00332     0.00880       0.02093   
..                ...       ...       ...         ...           ...   
110           0.00003   0.00232   0.00269     0.00696       0.03273   
111           0.00002   0.00182   0.00215     0.00546       0.03527   
112           0.00002   0.00189   0.00211     0.00568       0.01997   
113           0.00001   0.00100   0.00133     0.00301       0.02662   
114           0.00002   0.00169   0.00188     0.00506       0.02536   

     MDVP:Shimmer(dB)  ...  MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE  \
0               0.426  ...   0.02971      0.06545  0.02211  21.033  0.414783   
1               0.517  ...   0.03772      0.08771  0.01353  20.644  0.434969   
2               0.140  ...   0.01351      0.02337  0.00607  24.886  0.596040   
3               0.134  ...   0.01256      0.02487  0.00344  26.892  0.637420   
4               0.191  ...   0.01717      0.03218  0.01070  21.812  0.615551   
..                ...  ...       ...          ...      ...     ...       ...   
110             0.281  ...   0.02824      0.05139  0.02485  18.540  0.677131   
111             0.297  ...   0.02530      0.06165  0.01728  18.702  0.606273   
112             0.180  ...   0.01506      0.03350  0.02010  18.687  0.536102   
113             0.228  ...   0.02006      0.04426  0.01049  20.680  0.497480   
114             0.225  ...   0.01909      0.04137  0.01493  20.366  0.566849   

          DFA   spread1   spread2        D2       PPE  
0    0.815285 -4.813031  0.266482  2.301442  0.284654  
1    0.819235 -4.117501  0.334147  2.405554  0.368975  
2    0.764112 -5.634322  0.257682  1.854785  0.211756  
3    0.763262 -6.167603  0.183721  2.064693  0.163755  
4    0.773587 -5.498678  0.327769  2.322511  0.231571  
..        ...       ...       ...       ...       ...  
110  0.685057 -4.796845  0.397749  2.963799  0.277227  
111  0.661735 -5.585259  0.310746  2.465528  0.209863  
112  0.632631 -5.898673  0.213353  2.470746  0.189032  
113  0.630409 -6.132663  0.220617  2.576563  0.159777  
114  0.574282 -5.456811  0.345238  2.840556  0.232861  

[115 rows x 22 columns]

In [4]:
y = df['status']
y

0      1
1      1
2      1
3      1
4      1
      ..
110    0
111    0
112    0
113    0
114    0
Name: status, Length: 115, dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 42)

In [6]:
x_train.shape

(92, 22)

In [7]:
x_test.shape

(23, 22)

In [8]:
from sklearn.preprocessing import MinMaxScaler
min_max = MinMaxScaler()
x = min_max.fit_transform(x)
x

array([[0.19289918, 0.22320467, 0.0611575 , ..., 0.61494551, 0.52395445,
        0.74009974],
       [0.1726947 , 0.14457295, 0.29477133, ..., 0.81343189, 0.58607327,
        1.        ],
       [0.19457477, 0.14203566, 0.31695786, ..., 0.58913187, 0.25745489,
        0.51540828],
       ...,
       [0.69748114, 0.52349523, 0.13332477, ..., 0.45909858, 0.62497032,
        0.44536673],
       [0.69589086, 0.563323  , 0.63394142, ..., 0.48040656, 0.68810642,
        0.35519486],
       [0.82272943, 0.65446312, 0.14235612, ..., 0.84596588, 0.84561883,
        0.58045963]])

In [10]:
from sklearn.linear_model import LogisticRegression
Lr = LogisticRegression()
Lr.fit(x_train, y_train)

y_pred = Lr.predict(x)
print(y_pred)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("\nAccuracy score: ", accuracy_score(y, y_pred))
print("\nConfusion matrix: \n", confusion_matrix(y, y_pred))
print("\nClassification report: \n", classification_report(y, y_pred))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]

Accuracy score:  0.7391304347826086

Confusion matrix: 
 [[ 0 30]
 [ 0 85]]

Classification report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.74      1.00      0.85        85

    accuracy                           0.74       115
   macro avg       0.37      0.50      0.42       115
weighted avg       0.55      0.74      0.63       115



In [11]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

y_pred = dtc.predict(x)
print(y_pred)

print("\nAccuracy score: ", accuracy_score(y, y_pred))
print("\nConfusion matrix: \n", confusion_matrix(y, y_pred))
print("\nClassification report: \n", classification_report(y, y_pred))

[0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1
 1 1 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0]

Accuracy score:  0.4782608695652174

Confusion matrix: 
 [[24  6]
 [54 31]]

Classification report: 
               precision    recall  f1-score   support

           0       0.31      0.80      0.44        30
           1       0.84      0.36      0.51        85

    accuracy                           0.48       115
   macro avg       0.57      0.58      0.48       115
weighted avg       0.70      0.48      0.49       115



In [12]:
from sklearn.tree import ExtraTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

y_pred = dtc.predict(x)
print(y_pred)

print("\nAccuracy score: ", accuracy_score(y, y_pred))
print("\nConfusion matrix: \n", confusion_matrix(y, y_pred))
print("\nClassification report: \n", classification_report(y, y_pred))

[1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0
 0 1 1 0]

Accuracy score:  0.4956521739130435

Confusion matrix: 
 [[ 7 23]
 [35 50]]

Classification report: 
               precision    recall  f1-score   support

           0       0.17      0.23      0.19        30
           1       0.68      0.59      0.63        85

    accuracy                           0.50       115
   macro avg       0.43      0.41      0.41       115
weighted avg       0.55      0.50      0.52       115



In [13]:
from sklearn.ensemble import RandomForestClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

y_pred = dtc.predict(x)
print(y_pred)

print("\nAccuracy score: ", accuracy_score(y, y_pred))
print("\nConfusion matrix: \n", confusion_matrix(y, y_pred))
print("\nClassification report: \n", classification_report(y, y_pred))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]

Accuracy score:  0.7391304347826086

Confusion matrix: 
 [[ 0 30]
 [ 0 85]]

Classification report: 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.74      1.00      0.85        85

    accuracy                           0.74       115
   macro avg       0.37      0.50      0.42       115
weighted avg       0.55      0.74      0.63       115

